language: node_js
node_js:
  - "0.11"
  - "0.10"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7482f8068d15dc4fcc09
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false