// Generated by CoffeeScript 1.10.0
(function() {
  var i, j, len, mod, mods, ref;

  module.exports = {};

  mods = [require('./XbmcApi'), require('./TCPConnection'), require('./Player'), require('./Input'), require('./Handlers'), require('./Media'), require('./Notifications')];

  ref = ['XbmcApi', 'TCPConnection', 'Player', 'Input', 'Handlers', 'Media', 'Notifications'];
  for (i = j = 0, len = ref.length; j < len; i = ++j) {
    mod = ref[i];
    module.exports[mod] = mods[i];
  }

  module.exports.pubsub = require('./PubSub');

}).call(this);
